#### Today Topics
- Introduction to Data Analysis
- The information stored in a file is called data
- The complete study of data is called data science
- Aritificial Intelligence and Machine Learning are the parts of Data Science

<img src="ds.jpg" height=170px width=170px>

#### Data Sources
- Data in realtime/real world
    - 2types of data
        1. Discrete
            - This type of data is fixed/constant
            - Ex:Name,Roll number,Aadhar etc.
            - 2types of data
                1. Quantitative
                    - This type of data is organized on the basis of size/volume
                    - Ex:fize size(mb)
                2. Qualitative
                    - This type of data is categorized on the basis of quality
                    - Ex:feedback form
                        - good
                        - average
                        - excellent
                        - outstanding
        2. Continuous
            - this type of data is continuous in nature
            - Ex:height,weight, transactions etc.
- data in our devices
    - data is present in the forms of files such as 
    - .txt,.xls,.doc,.ppt,.mp3,.mp4,.jpg,.exe,.py,.apk etc
- data in statistics
    - 4 types of data
        1. Nominal data
            - this data is categorized on the basis of names
        2. Ordinal
            - the data points can be arranged in an order
                - ascending order/descending order
        3. Rational
            - Data in the form of p/q 
            - ratio or proportion
        4. Interval
            - data is present in a range(lower bound,upper bound)
            
            
- Now a days,everybody is using the data and generating the data,Hence, data is increasing day by day.

#### Data Science Modules
    1. Numpy
    2. Pandas
    3. Matplot library
    4. Searborn
    5. Scikit Learn

#### Numpy
- Numpy stands for Numerical Python used for the scientific computation of data
- if our data is numerical , the data is arranged in the array format 
- **installation of numpy**
    1. pip install numpy(local machine/device)
    2. import numpy(workspace)


In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

#### functions that supports to store data in a array format
1. np.array()
2. np.arange()
3. np.ones()
4. np.zeros()
5. np.full()
6. np.fill()
7. np.linspace()
8. np.diag()
9. np.random()
10. np.identity()
11. np.eye()

In [4]:
# array creation using tuple/list/set/dict
a=np.array((1,2,3,4,9))
print(a) # 1 dimensional array:only one row of element

[1 2 3 4 9]


In [6]:
# 2d array contains row and column
print(np.array([3,45,13,24,15]))
ar=np.array([[1,2,3],[4,5,6]])
print(ar)

[ 3 45 13 24 15]
[[1 2 3]
 [4 5 6]]


In [11]:
# array is the homogenous data structure that alllows only one type of data
# str/int/float 
char=np.array([chr(val) for val in range(65,72)])
print(char)

['A' 'B' 'C' 'D' 'E' 'F' 'G']


In [13]:
# float array
print(np.array({45.6,12.34,90.45,67.3,35.4}))

{67.3, 35.4, 90.45, 12.34, 45.6}


In [14]:
#conversion of 1d array into 2d and 3d
ar=np.arange(15).reshape(3,5)
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [17]:
# 1d into 3d: 45 values -->(3,15)-->(3,3,5) or(3,5,3)
ar=np.arange(45).reshape(3,5,3)
print(ar)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


In [18]:
print(np.arange(45).reshape(5,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [22]:
# 32 dimensional array
np.array([3,4,5,6],ndmin=32)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[3, 4,
                                      5, 6]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [26]:
o=np.ones(4)
print(o)
o2=np.ones((4,3),dtype=int)
print(o2)

[1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
z=np.zeros(5)
print(z)
z2=np.zeros((4,4),dtype=int)
z2

[0. 0. 0. 0. 0.]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
# full and fill
f=np.full(4,9) # 1d array filled with 9
print(f)
f2=np.full((4,5),8) # 2d array
print(f2)
f3=np.full((4,5,8),2) # 3d array:n,r,c,val
f3

[9 9 9 9]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


array([[[2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2]]])

In [33]:
#identity and eye--> diag--1 and rest is 0
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
# np.diag() creates the diagnal matrix/array
np.diag([4,5,6,7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [41]:
# it can get diagnal values of the existed array
arn=np.arange(25).reshape(5,5)
print(arn)
np.diag(arn)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  6, 12, 18, 24])

In [42]:
# linspace-->linear space --> equally separate the given range
# distribution of data points  in the given interval
np.linspace(4,8) # 4,5,6,7,8-->5-->50 partitions by default


array([4.        , 4.08163265, 4.16326531, 4.24489796, 4.32653061,
       4.40816327, 4.48979592, 4.57142857, 4.65306122, 4.73469388,
       4.81632653, 4.89795918, 4.97959184, 5.06122449, 5.14285714,
       5.2244898 , 5.30612245, 5.3877551 , 5.46938776, 5.55102041,
       5.63265306, 5.71428571, 5.79591837, 5.87755102, 5.95918367,
       6.04081633, 6.12244898, 6.20408163, 6.28571429, 6.36734694,
       6.44897959, 6.53061224, 6.6122449 , 6.69387755, 6.7755102 ,
       6.85714286, 6.93877551, 7.02040816, 7.10204082, 7.18367347,
       7.26530612, 7.34693878, 7.42857143, 7.51020408, 7.59183673,
       7.67346939, 7.75510204, 7.83673469, 7.91836735, 8.        ])

In [43]:
5/50

0.1

In [46]:
np.linspace(4,8,9).reshape(3,3)

array([[4. , 4.5, 5. ],
       [5.5, 6. , 6.5],
       [7. , 7.5, 8. ]])

#### random()
- random is the sub module of numpy used to generate random values in the given interval
- np.random.random()
- np.random.rand()
- np.random.randn()
- np.random.randint()
- np.random.randint(,)
- np.random.randint(,,)

In [48]:
np.random.random((3,3)) # random distribution/float values b/w 0 & 1

array([[0.65014965, 0.18116008, 0.06668208],
       [0.43759196, 0.26624542, 0.89798011],
       [0.61301443, 0.31309819, 0.56213532]])

In [49]:
np.random.rand(3,3)

array([[0.77004153, 0.70085687, 0.21373385],
       [0.82862354, 0.53907059, 0.90880659],
       [0.90449242, 0.19691574, 0.61750197]])

In [51]:
np.random.randn(3,3)

array([[ 0.91422153,  0.02500262,  0.28058976],
       [-0.88200011, -1.38506183, -1.13303373],
       [-0.25966637,  0.83378891, -1.34951337]])

In [61]:
print(np.random.randint(10000))
print(np.random.randint(100,200))
print(np.random.randint(10,20,2000).reshape(5,80,5))

8323
163
[[[16 14 17 16 19]
  [16 13 16 19 15]
  [11 14 18 11 12]
  ...
  [19 17 11 18 10]
  [14 10 10 19 11]
  [18 15 14 12 10]]

 [[16 15 10 12 18]
  [17 12 12 18 17]
  [12 13 18 18 11]
  ...
  [18 16 13 16 16]
  [10 19 10 11 12]
  [19 12 17 16 18]]

 [[12 17 12 14 13]
  [12 11 18 12 16]
  [12 12 19 17 10]
  ...
  [12 13 13 18 16]
  [11 12 16 18 12]
  [10 14 14 10 17]]

 [[15 15 19 15 18]
  [18 10 12 16 15]
  [13 16 19 18 15]
  ...
  [18 18 18 17 16]
  [14 19 10 16 11]
  [15 18 17 17 13]]

 [[12 13 15 17 11]
  [14 17 19 14 13]
  [10 13 15 15 11]
  ...
  [19 15 14 10 17]
  [16 19 19 17 11]
  [19 13 13 12 18]]]


In [62]:
2000->5*400->5*8*5

SyntaxError: invalid syntax (982341261.py, line 1)

#### Array Accessing and Slicing
- we can access the array elements using index
- index is of 2types
    1. Formal indexing
        - 2ways of representation
            1. forward/+ve indexing
                - travels from left to right
                - starting from 0 to len(iterable)-1
            2. backward/-ve indexing
                - travels from right to left
                - starts from -1 to -infinite
    2. Fancy indexing
        - condition as the index/integer

In [63]:
# create 2 equal size arrays
fml=np.arange(25).reshape(5,5)
print(fml)
ran=np.random.randint(45,80,25).reshape(5,5)
print(ran)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[57 52 56 64 74]
 [45 65 70 73 45]
 [67 74 78 60 50]
 [49 50 55 60 61]
 [50 74 71 77 60]]


In [64]:
fml[0] # first row of elements

array([0, 1, 2, 3, 4])

In [65]:
fml[3] # 4th row

array([15, 16, 17, 18, 19])

In [66]:
fml[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
fml[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
#2d indexing-->[r][c]
fml[2][4]

14

In [69]:
fml

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
fml[0][2]

2

In [72]:
# slicing both rows&cols
fml[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [73]:
# alternate cols in alternate row
fml[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [74]:
fml[::2,::2] # 3d silicing

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [75]:
# fancy indexing-->condition
ran

array([[57, 52, 56, 64, 74],
       [45, 65, 70, 73, 45],
       [67, 74, 78, 60, 50],
       [49, 50, 55, 60, 61],
       [50, 74, 71, 77, 60]])

In [76]:
ran>65 # resulting in boolean array

array([[False, False, False, False,  True],
       [False, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True, False]])

In [77]:
ran[ran>65]

array([74, 70, 73, 67, 74, 78, 74, 71, 77])

In [78]:
ran[ran>65].reshape(3,3)

array([[74, 70, 73],
       [67, 74, 78],
       [74, 71, 77]])

In [82]:
len(ran[ran>65])

9

#### scientific computation 
- mean()
- std()
- dot()
- min()
- max()
- sum()
- log()
- exp()

In [88]:
ran.T # transpose

array([[57, 45, 67, 49, 50],
       [52, 65, 74, 50, 74],
       [56, 70, 78, 55, 71],
       [64, 73, 60, 60, 77],
       [74, 45, 50, 61, 60]])

In [85]:
ran.transpose() # rows will be arranged as cols

array([[57, 45, 67, 49, 50],
       [52, 65, 74, 50, 74],
       [56, 70, 78, 55, 71],
       [64, 73, 60, 60, 77],
       [74, 45, 50, 61, 60]])

In [96]:
# min,max,sum,dot,mean,std,log,exp of the arrays
print(ran.min())
print(np.min(ran))
print(ran.max())
print(np.max(ran))
print(ran.sum())
print(np.sum(ran))
print(ran.mean())
print(np.mean(ran))
print(ran.dot(fml))
print(np.dot(ran,fml))
print(ran.std())
print(np.std(ran))
print(np.exp(ran))
print(np.log(ran))

45
45
78
78
1537
1537
61.48
61.48
[[3260 3563 3866 4169 4472]
 [3020 3318 3616 3914 4212]
 [3050 3379 3708 4037 4366]
 [2920 3195 3470 3745 4020]
 [3435 3767 4099 4431 4763]]
[[3260 3563 3866 4169 4472]
 [3020 3318 3616 3914 4212]
 [3050 3379 3708 4037 4366]
 [2920 3195 3470 3745 4020]
 [3435 3767 4099 4431 4763]]
10.222015456846073
10.222015456846073
[[5.68572000e+24 3.83100800e+22 2.09165950e+24 6.23514908e+27
  1.37338298e+32]
 [3.49342711e+19 1.69488924e+28 2.51543867e+30 5.05239363e+31
  3.49342711e+19]
 [1.25236317e+29 1.37338298e+32 7.49841700e+33 1.14200739e+26
  5.18470553e+21]
 [1.90734657e+21 5.18470553e+21 7.69478527e+23 1.14200739e+26
  3.10429794e+26]
 [5.18470553e+21 1.37338298e+32 6.83767123e+30 2.75851345e+33
  1.14200739e+26]]
[[4.04305127 3.95124372 4.02535169 4.15888308 4.30406509]
 [3.80666249 4.17438727 4.24849524 4.29045944 3.80666249]
 [4.20469262 4.30406509 4.35670883 4.09434456 3.91202301]
 [3.8918203  3.91202301 4.00733319 4.09434456 4.11087386]
 [3.91202301 

#### pandas module
- Pandas stands for panelData 
- if our data is in the form of table/panel 
- it has 2 data structures
    1. Series
        - the data is arranged sequentially
        - pandas.Series(data)
    2. DataFrame
        - the data is arranged in the table
        - pandas.DataFrame(data)

In [1]:
import pandas as pd

In [2]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat

In [3]:
# creating the series with tuple/list/set/dict
pd.Series((4,5,6,10,9))

0     4
1     5
2     6
3    10
4     9
dtype: int64

In [4]:
pd.Series(['a',9,45,67])

0     a
1     9
2    45
3    67
dtype: object

In [5]:
pd.Series({'st':[1,2,3],'roll':(4,5,6)})

st      [1, 2, 3]
roll    (4, 5, 6)
dtype: object

In [8]:
import numpy as np
pd.Series(np.arange(40,51))

0     40
1     41
2     42
3     43
4     44
5     45
6     46
7     47
8     48
9     49
10    50
dtype: int32

In [9]:
# date_range
pd.date_range("2025-03-10","2025-03-25")

DatetimeIndex(['2025-03-10', '2025-03-11', '2025-03-12', '2025-03-13',
               '2025-03-14', '2025-03-15', '2025-03-16', '2025-03-17',
               '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21',
               '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25'],
              dtype='datetime64[ns]', freq='D')

In [12]:
# user index
temp=np.random.randint(35,43,10)
pd.Series(temp,index=[pd.date_range("2025-03-10","2025-03-19")])

2025-03-10    41
2025-03-11    41
2025-03-12    36
2025-03-13    37
2025-03-14    40
2025-03-15    38
2025-03-16    36
2025-03-17    39
2025-03-18    42
2025-03-19    40
dtype: int32

In [16]:
# data frame contains rows and columns
# user index: 2columns
dic={'date':pd.date_range("2025-03-10",periods=10),
    'temp':np.random.randint(35,43,10),}
pd.DataFrame(dic)

date  temp
0 2025-03-10    35
1 2025-03-11    39
2 2025-03-12    35
3 2025-03-13    39
4 2025-03-14    37
5 2025-03-15    39
6 2025-03-16    36
7 2025-03-17    40
8 2025-03-18    40
9 2025-03-19    37

In [20]:
pd.DataFrame([np.arange(10)],[np.arange(20,30)])

0  1  2  3  4  5  6  7  8  9
20  0  1  2  3  4  5  6  7  8  9
21  0  1  2  3  4  5  6  7  8  9
22  0  1  2  3  4  5  6  7  8  9
23  0  1  2  3  4  5  6  7  8  9
24  0  1  2  3  4  5  6  7  8  9
25  0  1  2  3  4  5  6  7  8  9
26  0  1  2  3  4  5  6  7  8  9
27  0  1  2  3  4  5  6  7  8  9
28  0  1  2  3  4  5  6  7  8  9
29  0  1  2  3  4  5  6  7  8  9

In [21]:
# creating the dataframe and merging,joining and concatenation
# create the followind dataframe
int  float str
--   ----   ---
--   ----   ---
--   ----   ---
--   ----   ---
--   ----   ---

SyntaxError: invalid syntax (273611300.py, line 3)

In [23]:
df=pd.DataFrame({'int':[9,8,7,6,5],'float':(3.5,4.9,5.9,6.4,9.3),
             'str':['a','b','c','d','e']})
df

int  float str
0    9    3.5   a
1    8    4.9   b
2    7    5.9   c
3    6    6.4   d
4    5    9.3   e

In [25]:
# combining the multiple dfs
df=pd.DataFrame({'int':[9,8,7,6,5],'float':(3.5,4.9,5.9,6.4,9.3),
             'str':['a','b','c','d','e']})
df2=pd.DataFrame({'int':[9,8,10,6,5],'float':(3.5,4.9,5.7,6.4,9.3),
             'str':['a','b','k','d','e']})
df

int  float str
0    9    3.5   a
1    8    4.9   b
2    7    5.9   c
3    6    6.4   d
4    5    9.3   e

In [26]:
df2

int  float str
0    9    3.5   a
1    8    4.9   b
2   10    5.7   k
3    6    6.4   d
4    5    9.3   e

In [27]:
df.merge(df2) # non-similar sample will be deleted

int  float str
0    9    3.5   a
1    8    4.9   b
2    6    6.4   d
3    5    9.3   e

In [32]:
pd.concat([df,df2]) # similar cols,data of df2 is added to df

int  float str
0    9    3.5   a
1    8    4.9   b
2    7    5.9   c
3    6    6.4   d
4    5    9.3   e
0    9    3.5   a
1    8    4.9   b
2   10    5.7   k
3    6    6.4   d
4    5    9.3   e

In [33]:
df3=pd.DataFrame({'num':[9,8,7,6,5],'gpa':(3.5,4.9,5.9,6.4,9.3),
             'student':['a','b','c','d','e']})
df4=pd.DataFrame({'int':[9,8,7,6,5],'float':(3.5,4.9,5.9,6.4,9.3),
             'str':['a','b','c','d','e']})
df3

num  gpa student
0    9  3.5       a
1    8  4.9       b
2    7  5.9       c
3    6  6.4       d
4    5  9.3       e

In [34]:
df4

int  float str
0    9    3.5   a
1    8    4.9   b
2    7    5.9   c
3    6    6.4   d
4    5    9.3   e

In [38]:
new=df3.join(df4) # adding the new cols in the sheet
new.index=['R1','R2','R3','R4','R5']
new

num  gpa student  int  float str
R1    9  3.5       a    9    3.5   a
R2    8  4.9       b    8    4.9   b
R3    7  5.9       c    7    5.9   c
R4    6  6.4       d    6    6.4   d
R5    5  9.3       e    5    9.3   e

In [40]:
# accessing and slicing of the dataframe
# df depends upon the column 
new['student']

R1    a
R2    b
R3    c
R4    d
R5    e
Name: student, dtype: object

In [41]:
new[['int','num','gpa']]

int  num  gpa
R1    9    9  3.5
R2    8    8  4.9
R3    7    7  5.9
R4    6    6  6.4
R5    5    5  9.3

In [46]:
new.iloc[3] # iloc:index locate: row wise data

num          6
gpa        6.4
student      d
int          6
float      6.4
str          d
Name: R4, dtype: object

In [47]:
new

num  gpa student  int  float str
R1    9  3.5       a    9    3.5   a
R2    8  4.9       b    8    4.9   b
R3    7  5.9       c    7    5.9   c
R4    6  6.4       d    6    6.4   d
R5    5  9.3       e    5    9.3   e

In [48]:
new.iloc[:] # considers all the rows

num  gpa student  int  float str
R1    9  3.5       a    9    3.5   a
R2    8  4.9       b    8    4.9   b
R3    7  5.9       c    7    5.9   c
R4    6  6.4       d    6    6.4   d
R5    5  9.3       e    5    9.3   e

In [50]:
new.iloc[:,3:] # all the rows,cols from 3rd index

int  float str
R1    9    3.5   a
R2    8    4.9   b
R3    7    5.9   c
R4    6    6.4   d
R5    5    9.3   e

In [51]:
new.iloc[2:]

num  gpa student  int  float str
R3    7  5.9       c    7    5.9   c
R4    6  6.4       d    6    6.4   d
R5    5  9.3       e    5    9.3   e

#### working with .csv file
- .xls file saved with extension .csv
- comma separated values
- data belongs to any organization

In [1]:
import pandas as pd
data=pd.read_csv("Students.csv")
data

S.No. Registration Id                             Name  \
0        1      23BA1A4271                        K.Karthik   
1        2      23BQ1A05N1                  Vadlamudi Ramya   
2        3      23BQ1A4201  Adhimulam Bhargav Sai Viswanath   
3        4      23BQ1A4202       Agepati Venkata Sai Charan   
4        5      23BQ1A4203             Akkala Umesh Karthik   
..     ...             ...                              ...   
379    380      24BQ5A6138                     Shaik Vaseem   
380    381      24BQ5A6139        Thotakura Amarendra Kumar   
381    382      24BQ5A6140                 Thotakura Mahesh   
382    383      24BQ5A6143              D. Venkatadri Naidu   
383    384      24bq5a6121          Chejarla Vishnu Vardhan   

                                  Email   Mobile No  
0           karthikkakumanu09@gmail.com  9848139894  
1            vadlamudiramya87@gmail.com  7337001554  
2       bhargavsaiadhimulam12@gmail.com  7013833594  
3               cherry123abba@gmail.com  9618223895  
4            umeshkarthik2006@gmail.com  8329610575  
..                                  ...         ...  
379            vaseemshaik090@gmail.com  7995979089  
380   kumarthotakuraamarendra@gmail.com  8499903775  
381       thotakuramahesh0693@gmail.com  9618752221  
382   venkatchowdaryduggineni@gmail.com  9133913683  
383  Chejarlavishnuvardhan603@gmail.com  9059471263  

[384 rows x 5 columns]

In [54]:
data.Email

0             karthikkakumanu09@gmail.com
1              vadlamudiramya87@gmail.com
2         bhargavsaiadhimulam12@gmail.com
3                 cherry123abba@gmail.com
4              umeshkarthik2006@gmail.com
                      ...                
379              vaseemshaik090@gmail.com
380     kumarthotakuraamarendra@gmail.com
381         thotakuramahesh0693@gmail.com
382     venkatchowdaryduggineni@gmail.com
383    Chejarlavishnuvardhan603@gmail.com
Name: Email, Length: 384, dtype: object

In [55]:
data.Email.value_counts() # frequency of item

marrikavya90@gmail.com                2
savarideepthi@gmail.com               2
andevenkatavaibhav@gmail.com          2
bhargavigoud123123@gmail.com          2
tokalagopichand9@gmail.com            2
                                     ..
pondurijagadish@gmail.com             1
saswathapodila111@gmail.com           1
pikkiliharika387@gmail.com            1
pentelakarthikeya01@gmail.com         1
Chejarlavishnuvardhan603@gmail.com    1
Name: Email, Length: 379, dtype: int64

In [58]:
data.Name.value_counts()

Marri Kavya Lakshmi             2
Savari Venkata Durga Deepthi    2
Ande Venkata Vaibhav            2
Pandula Bhargavi                2
Tokala Gopichand                2
                               ..
Ponduri Jagadish                1
Podila Saswitha Rani            1
Pikkili Harika                  1
Karthikeya Pentela              1
Chejarla Vishnu Vardhan         1
Name: Name, Length: 379, dtype: int64

In [59]:
data.head() # first 5 samples of the data

S.No. Registration Id                             Name  \
0      1      23BA1A4271                        K.Karthik   
1      2      23BQ1A05N1                  Vadlamudi Ramya   
2      3      23BQ1A4201  Adhimulam Bhargav Sai Viswanath   
3      4      23BQ1A4202       Agepati Venkata Sai Charan   
4      5      23BQ1A4203             Akkala Umesh Karthik   

                             Email   Mobile No  
0      karthikkakumanu09@gmail.com  9848139894  
1       vadlamudiramya87@gmail.com  7337001554  
2  bhargavsaiadhimulam12@gmail.com  7013833594  
3          cherry123abba@gmail.com  9618223895  
4       umeshkarthik2006@gmail.com  8329610575

In [61]:
data.head(3) # first 3 samples

S.No. Registration Id                             Name  \
0      1      23BA1A4271                        K.Karthik   
1      2      23BQ1A05N1                  Vadlamudi Ramya   
2      3      23BQ1A4201  Adhimulam Bhargav Sai Viswanath   

                             Email   Mobile No  
0      karthikkakumanu09@gmail.com  9848139894  
1       vadlamudiramya87@gmail.com  7337001554  
2  bhargavsaiadhimulam12@gmail.com  7013833594

In [62]:
data.tail() # last 5 samples by default

S.No. Registration Id                       Name  \
379    380      24BQ5A6138               Shaik Vaseem   
380    381      24BQ5A6139  Thotakura Amarendra Kumar   
381    382      24BQ5A6140           Thotakura Mahesh   
382    383      24BQ5A6143        D. Venkatadri Naidu   
383    384      24bq5a6121    Chejarla Vishnu Vardhan   

                                  Email   Mobile No  
379            vaseemshaik090@gmail.com  7995979089  
380   kumarthotakuraamarendra@gmail.com  8499903775  
381       thotakuramahesh0693@gmail.com  9618752221  
382   venkatchowdaryduggineni@gmail.com  9133913683  
383  Chejarlavishnuvardhan603@gmail.com  9059471263

In [63]:
data.tail(3) # last n samples

S.No. Registration Id                     Name  \
381    382      24BQ5A6140         Thotakura Mahesh   
382    383      24BQ5A6143      D. Venkatadri Naidu   
383    384      24bq5a6121  Chejarla Vishnu Vardhan   

                                  Email   Mobile No  
381       thotakuramahesh0693@gmail.com  9618752221  
382   venkatchowdaryduggineni@gmail.com  9133913683  
383  Chejarlavishnuvardhan603@gmail.com  9059471263

In [68]:
data.sample() # random sample/row

S.No. Registration Id           Name                     Email  \
341    342      24BQ5A4216  Palla Vennela  pallavennela88@gmail.com   

      Mobile No  
341  9959606346

In [69]:
data.sample(20) # n random samples

S.No. Registration Id                       Name  \
51      52      23BQ1A4253     Gollapudi.Sai Geethika   
68      69      23BQ1A4274              Kasa Harendra   
353    354      24BQ5A6109                Meda Harika   
230    231      23BQ1A6161            Kethavath Kavya   
347    348      24BQ5A6102   Chopparapu Veera Brahmam   
354    355      24BQ5A6110        Marri Kavya Lakshmi   
152    153      23BQ1A42H1  Thammisetty Vamsi Krishna   
277    278      23BQ1A61B1          Puli Yogendra Sai   
66      67      23BQ1A4272                      Rahul   
120    121      23BQ1A42D7            Peddu Tanishkha   
198    199      23BQ1A6123       Chintapalli Teja Sri   
149    150      23BQ1A42G7          Sree Manju Veeran   
171    172      23BQ1A42I9             Yele Harshitha   
137    138      23BQ1A42F4               Sana Kalpana   
133    134      23BQ1A42F0             Vijay Rayapudi   
24      25      23BQ1A4223      B Vamsi Krishna Reddy   
343    344      24BQ5A4218      Vellaturi Jyoshna Sri   
109    110      23BQ1A42C5                Nandeu Teja   
6        7      23BQ1A4205        Ala Ramya Sesha Sri   
321    322      23BQ1A61F7      Varikuti Dharaneeswar   

                                  Email   Mobile No  
51   gollapudisaigeethika2006@gmail.com  9492261228  
68               harendrakasa@gmail.com  9949930395  
353            harikameda2006@gmail.com  9391470798  
230          kavyakethavath85@gmail.com  7671081718  
347   chopparapuveerabrahamam@gmail.com  9347601671  
354              marrikavya90@gmail.com  9959734009  
152                   tvk6673@gmail.com  7050174143  
277           yogendrasaipuli@gmail.com  9182243331  
66        kanaparthirahul2005@gmail.com  9346575129  
120            tanishkhapeddu@gmail.com  9705481239  
198       tejasrichintapalli5@gmail.com  9121454512  
149          ksreemanjuveeran@gmail.com  9491381002  
171         harshithayele2005@gmail.com  7306717274  
137              kalpanasana4@gmail.com  7989219968  
133           vijayrayapudi44@gmail.com  9989870852  
24                  konda8052@gmail.com  9515169914  
343            jyoshnasri1406@gmail.com  9912472740  
109              tejanandru79@gmail.com  8074959537  
6            ramyaseshasriala@gmail.com  7207394189  
321    varikutidharaneeswar13@gmail.com  9391374095

In [70]:
data.describe() # statistics of the data

S.No.     Mobile No
count  384.000000  3.840000e+02
mean   192.500000  8.742263e+09
std    110.995495  8.797045e+08
min      1.000000  6.302226e+09
25%     96.750000  8.019265e+09
50%    192.500000  9.005252e+09
75%    288.250000  9.441146e+09
max    384.000000  9.989871e+09

In [71]:
data.info()  # textual info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   S.No.            384 non-null    int64 
 1   Registration Id  384 non-null    object
 2   Name             384 non-null    object
 3   Email            384 non-null    object
 4   Mobile No        384 non-null    int64 
dtypes: int64(2), object(3)
memory usage: 15.1+ KB


In [72]:
data.isnull()

S.No.  Registration Id   Name  Email  Mobile No
0    False            False  False  False      False
1    False            False  False  False      False
2    False            False  False  False      False
3    False            False  False  False      False
4    False            False  False  False      False
..     ...              ...    ...    ...        ...
379  False            False  False  False      False
380  False            False  False  False      False
381  False            False  False  False      False
382  False            False  False  False      False
383  False            False  False  False      False

[384 rows x 5 columns]

In [73]:
data.isna()

S.No.  Registration Id   Name  Email  Mobile No
0    False            False  False  False      False
1    False            False  False  False      False
2    False            False  False  False      False
3    False            False  False  False      False
4    False            False  False  False      False
..     ...              ...    ...    ...        ...
379  False            False  False  False      False
380  False            False  False  False      False
381  False            False  False  False      False
382  False            False  False  False      False
383  False            False  False  False      False

[384 rows x 5 columns]

In [74]:
data.sum()

S.No.                                                          73920
Registration Id    23BA1A427123BQ1A05N123BQ1A420123BQ1A420223BQ1A...
Name               K.KarthikVadlamudi RamyaAdhimulam Bhargav Sai ...
Email              karthikkakumanu09@gmail.comvadlamudiramya87@gm...
Mobile No                                              3357029061039
dtype: object

In [75]:
# multiple cols [['','']]
data['year']=3
data

S.No. Registration Id                             Name  \
0        1      23BA1A4271                        K.Karthik   
1        2      23BQ1A05N1                  Vadlamudi Ramya   
2        3      23BQ1A4201  Adhimulam Bhargav Sai Viswanath   
3        4      23BQ1A4202       Agepati Venkata Sai Charan   
4        5      23BQ1A4203             Akkala Umesh Karthik   
..     ...             ...                              ...   
379    380      24BQ5A6138                     Shaik Vaseem   
380    381      24BQ5A6139        Thotakura Amarendra Kumar   
381    382      24BQ5A6140                 Thotakura Mahesh   
382    383      24BQ5A6143              D. Venkatadri Naidu   
383    384      24bq5a6121          Chejarla Vishnu Vardhan   

                                  Email   Mobile No  year  
0           karthikkakumanu09@gmail.com  9848139894     3  
1            vadlamudiramya87@gmail.com  7337001554     3  
2       bhargavsaiadhimulam12@gmail.com  7013833594     3  
3               cherry123abba@gmail.com  9618223895     3  
4            umeshkarthik2006@gmail.com  8329610575     3  
..                                  ...         ...   ...  
379            vaseemshaik090@gmail.com  7995979089     3  
380   kumarthotakuraamarendra@gmail.com  8499903775     3  
381       thotakuramahesh0693@gmail.com  9618752221     3  
382   venkatchowdaryduggineni@gmail.com  9133913683     3  
383  Chejarlavishnuvardhan603@gmail.com  9059471263     3  

[384 rows x 6 columns]

In [79]:
# repeated data -->delete
data.Name.value_counts()==2

Marri Kavya Lakshmi              True
Savari Venkata Durga Deepthi     True
Ande Venkata Vaibhav             True
Pandula Bhargavi                 True
Tokala Gopichand                 True
                                ...  
Ponduri Jagadish                False
Podila Saswitha Rani            False
Pikkili Harika                  False
Karthikeya Pentela              False
Chejarla Vishnu Vardhan         False
Name: Name, Length: 379, dtype: bool

In [82]:
data.drop(data.Name.value_counts()==2)

KeyError: '[True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False] not found in axis'

In [83]:
help(data.drop)

Help on method drop in module pandas.core.frame:

drop(labels=None, axis: 'Axis' = 0, index=None, columns=None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'str' = 'raise') method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.
    
    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the `user guide <advanced.shown_levels>`
    for more information about the now unused levels.
    
    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-l

In [97]:
data.dropna()

S.No. Registration Id                             Name  \
0        1      23BA1A4271                        K.Karthik   
1        2      23BQ1A05N1                  Vadlamudi Ramya   
2        3      23BQ1A4201  Adhimulam Bhargav Sai Viswanath   
3        4      23BQ1A4202       Agepati Venkata Sai Charan   
4        5      23BQ1A4203             Akkala Umesh Karthik   
..     ...             ...                              ...   
379    380      24BQ5A6138                     Shaik Vaseem   
380    381      24BQ5A6139        Thotakura Amarendra Kumar   
381    382      24BQ5A6140                 Thotakura Mahesh   
382    383      24BQ5A6143              D. Venkatadri Naidu   
383    384      24bq5a6121          Chejarla Vishnu Vardhan   

                                  Email   Mobile No  year  
0           karthikkakumanu09@gmail.com  9848139894     3  
1            vadlamudiramya87@gmail.com  7337001554     3  
2       bhargavsaiadhimulam12@gmail.com  7013833594     3  
3               cherry123abba@gmail.com  9618223895     3  
4            umeshkarthik2006@gmail.com  8329610575     3  
..                                  ...         ...   ...  
379            vaseemshaik090@gmail.com  7995979089     3  
380   kumarthotakuraamarendra@gmail.com  8499903775     3  
381       thotakuramahesh0693@gmail.com  9618752221     3  
382   venkatchowdaryduggineni@gmail.com  9133913683     3  
383  Chejarlavishnuvardhan603@gmail.com  9059471263     3  

[384 rows x 6 columns]

In [102]:
data['Name'].value_counts()==2

Marri Kavya Lakshmi              True
Savari Venkata Durga Deepthi     True
Ande Venkata Vaibhav             True
Pandula Bhargavi                 True
Tokala Gopichand                 True
                                ...  
Ponduri Jagadish                False
Podila Saswitha Rani            False
Pikkili Harika                  False
Karthikeya Pentela              False
Chejarla Vishnu Vardhan         False
Name: Name, Length: 379, dtype: bool

In [106]:
data[data['Name'].value_counts()==2] # tmrw session

C:\Users\ruthu\AppData\Local\Temp\ipykernel_24884\2934576820.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['Name'].value_counts()==2]


IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [3]:
data[['S.No.','Email']]

S.No.                               Email
0        1         karthikkakumanu09@gmail.com
1        2          vadlamudiramya87@gmail.com
2        3     bhargavsaiadhimulam12@gmail.com
3        4             cherry123abba@gmail.com
4        5          umeshkarthik2006@gmail.com
..     ...                                 ...
379    380            vaseemshaik090@gmail.com
380    381   kumarthotakuraamarendra@gmail.com
381    382       thotakuramahesh0693@gmail.com
382    383   venkatchowdaryduggineni@gmail.com
383    384  Chejarlavishnuvardhan603@gmail.com

[384 rows x 2 columns]

In [8]:
data

S.No. Registration Id                             Name  \
0        1      23BA1A4271                        K.Karthik   
1        2      23BQ1A05N1                  Vadlamudi Ramya   
2        3      23BQ1A4201  Adhimulam Bhargav Sai Viswanath   
3        4      23BQ1A4202       Agepati Venkata Sai Charan   
4        5      23BQ1A4203             Akkala Umesh Karthik   
..     ...             ...                              ...   
379    380      24BQ5A6138                     Shaik Vaseem   
380    381      24BQ5A6139        Thotakura Amarendra Kumar   
381    382      24BQ5A6140                 Thotakura Mahesh   
382    383      24BQ5A6143              D. Venkatadri Naidu   
383    384      24bq5a6121          Chejarla Vishnu Vardhan   

                                  Email   Mobile No  
0           karthikkakumanu09@gmail.com  9848139894  
1            vadlamudiramya87@gmail.com  7337001554  
2       bhargavsaiadhimulam12@gmail.com  7013833594  
3               cherry123abba@gmail.com  9618223895  
4            umeshkarthik2006@gmail.com  8329610575  
..                                  ...         ...  
379            vaseemshaik090@gmail.com  7995979089  
380   kumarthotakuraamarendra@gmail.com  8499903775  
381       thotakuramahesh0693@gmail.com  9618752221  
382   venkatchowdaryduggineni@gmail.com  9133913683  
383  Chejarlavishnuvardhan603@gmail.com  9059471263  

[384 rows x 5 columns]

In [11]:
data.Mobile No # due to the space in the middle of col

SyntaxError: invalid syntax (3796686503.py, line 1)

In [12]:
data['Mobile No']

0      9848139894
1      7337001554
2      7013833594
3      9618223895
4      8329610575
          ...    
379    7995979089
380    8499903775
381    9618752221
382    9133913683
383    9059471263
Name: Mobile No, Length: 384, dtype: int64

In [13]:
data['Mobile No']<8907654321

0      False
1       True
2       True
3      False
4       True
       ...  
379     True
380     True
381    False
382    False
383    False
Name: Mobile No, Length: 384, dtype: bool

In [14]:
data['Mobile No'].sum()

3357029061039

In [15]:
data['Name'].sum()

'K.KarthikVadlamudi RamyaAdhimulam Bhargav Sai ViswanathAgepati Venkata Sai CharanAkkala Umesh KarthikAkkinapalli VigneshAla Ramya Sesha SriAla Venu GopalAllamudi Ajay SuryaAmara Venkata Lakshmi TanujaAnati Madhu KrishnaAngati Arun PalAnkem Sai DhanushAthmakuri Poorna SahasraBaddigam Venkata TriveniBalabhadra SwathikaBandikatla SeshanjaliBandla VarshithaMohan SrihariMeghana BezawadaBhuvanagiri BhavaniBitra BhavaniBitra Jaya SriBodepudi Naga SoumyaB Vamsi Krishna ReddyBolagani Baby PrasannaB VenkateshBonam Raja SekharCh Gnana DeepCheeraboyina LokeswariCherukuri Supriya SundariChinta Venkata MadhuriChiruguri NissiChodagiri Raja Prabhu Darshan RoyalChandralekhaDarla SrikanthDerangula VishnuvardhanD.Vinay Kumar ReddyDomathoti RahulDudekula Khaja ValiDuggineni PavaniEnakalla Jeevan KumarEvuri Hari Thrinath ReddyGadamsetty.G L Narasimha Hanuma SakethGadde Bhagya AnjaliLohitha GajulaGalla SantoshGanduri RajeshwarGavini KeerthiGhanta Sri KameshuGogula KarthiGollapudi.Sai GeethikaGopidesi Durga

In [16]:
data.drop('Name')

KeyError: "['Name'] not found in axis"